FROM oven/bun:1.0 as base
WORKDIR /usr/src/app

# ---- Dependencies Stage ----
FROM base as deps
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# ---- Build Stage ----
FROM base as builder
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

# ---- Production Stage ----
FROM oven/bun:1.0-slim as production
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/src ./src
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/tsconfig.json ./tsconfig.json
EXPOSE 4000
CMD ["bun", "src/server.ts"]